---

language: java

jdk:
  - oraclejdk8

#services:
#  - cassandra

before_script:
  - export CLASSPATH=tools/tablesaw-1.2.6.jar

script:
  - java make clean test-all

before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.0.14/apache-cassandra-3.0.14-bin.tar.gz && tar -xvzf apache-cassandra-3.0.14-bin.tar.gz && sudo sh apache-cassandra-3.0.14/bin/cassandra
