---

language: java

jdk:
  - oraclejdk8
dist: trusty

#services:
#  - cassandra

before_script:
  - export CLASSPATH=tools/tablesaw-1.2.6.jar

script:
  - java make ivy-retrieve;java make clean test-all

before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.11.5/apache-cassandra-3.11.5-bin.tar.gz && tar -xvzf apache-cassandra-3.11.5-bin.tar.gz && sudo sh apache-cassandra-3.11.5-bin.tar.gz/bin/cassandra -R
